# These are values for the dynamic parameters of the sr305 camera
# Usage:
#
# (from this directory)
# rosparam load sr305.yaml
sr305:
  spatial:
    filter_magnitude: 2
    filter_smooth_alpha: 0.5
    filter_smooth_delta: 24
    frames_queue_size: 16
    holes_fill: 2
    stream_filter: 1
    stream_format_filter: 1
    stream_index_filter: -1
  decimation:
    filter_magnitude: 2
    frames_queue_size: 16
    stream_filter: 1
    stream_format_filter: 1
    stream_index_filter: -1
  pointcloud:
    filter_magnitude: 2
    frames_queue_size: 1
    stream_filter: 2
    stream_format_filter: 6
    stream_index_filter: 1
  rgb_camera:
    backlight_compensation: 2
    brightness: 1
    contrast: 51
    enable_auto_exposure: true
    enable_auto_white_balance: true
    exposure: 39
    frames_queue_size: 16
    gain: 71
    gamma: 299
    hue: 0
    saturation: 64
    sharpness: 51
    white_balance: 4144.0
  temporal:
    filter_smooth_alpha: 0.52
    filter_smooth_delta: 1
    frames_queue_size: 8
    holes_fill: 3
    stream_filter: 1
    stream_format_filter: 1
    stream_index_filter: -1
  coded_light_depth_sensor:
    #accuracy: 2
    #confidence_threshold: 5
    #filter_option: 5
    #frames_queue_size: 1
    #laser_power: 1
    #motion_range: 100
    visual_preset: 8
